<a href="https://colab.research.google.com/github/jayx003/Machine-Learning/blob/main/ML3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Logistic Regression**

In [1]:
file_path = 'https://raw.githubusercontent.com/hakimyameen/Datasets/refs/heads/main/heart.csv'

In [2]:
import pandas as pd
heart = pd.read_csv(file_path)
heart[:2]

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1

In [4]:
heart['target'].value_counts()

target
1    50490
0    42228
Name: count, dtype: int64